spring:
  profiles:
    active: '@activatedProperties@'
  redis:
    host: 39.104.88.65
    password: laky@123
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 100
      max-wait: -1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss